const API_BASE = process.argv[2] || 'http://localhost:3000/api'

const words = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；遗弃' },
  { word: 'abnormal', phonetic: '/æbˈnɔːrml/', meaning: 'adj. 异常的' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: 'v. 废除；废止' },
  { word: 'absent', phonetic: '/ˈæbsənt/', meaning: 'adj. 缺席的；不在的' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', meaning: 'adj. 绝对的；完全的' },
  { word: 'absorb', phonetic: '/əbˈzɔːrb/', meaning: 'v. 吸收；使全神贯注' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的 n. 摘要' },
  { word: 'abundant', phonetic: '/əˈbʌndənt/', meaning: 'adj. 丰富的；充裕的' },
  { word: 'abuse', phonetic: '/əˈbjuːz/', meaning: 'v./n. 滥用；虐待' },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速' },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道；进入 v. 存取' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；提供住宿' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴；伴随' },
  { word: 'accomplish', phonetic: '/əˈkɒmplɪʃ/', meaning: 'v. 完成；实现' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户；描述 v. 解释' },
  { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: 'v. 积累；堆积' },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 精确的；准确的' },
  { word: 'accuse', phonetic: '/əˈkjuːz/', meaning: 'v. 控告；指责' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 达到；实现' },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: 'v. 承认；感谢' },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', meaning: 'v. 获得；学到' },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 充足的；适当的' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整；适应' },
  { word: 'admire', phonetic: '/ədˈmaɪər/', meaning: 'v. 钦佩；羡慕' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认；准许进入' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: 'v. 采纳；收养' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: 'v./n. 前进；进步' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: 'n. 优势；有利条件' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', meaning: 'v. 做广告；宣传' },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: 'v. 提倡；拥护' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响；感动' },
  { word: 'afford', phonetic: '/əˈfɔːrd/', meaning: 'v. 负担得起；提供' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', meaning: 'adj. 侵略的；好斗的' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: 'v. 分配；拨出' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: 'n. 津贴；零用钱' },
  { word: 'alter', phonetic: '/ˈɔːltər/', meaning: 'v. 改变；修改' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', meaning: 'adj. 替代的 n. 选择' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心；抱负' },
  { word: 'amuse', phonetic: '/əˈmjuːz/', meaning: 'v. 使娱乐；逗乐' },
  { word: 'analyze', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布；通知' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 每年的 n. 年刊' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: 'v. 预期；期望' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', meaning: 'n. 焦虑；担忧' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: 'v. 呼吁；上诉 n. 吸引力' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', meaning: 'n. 食欲；欲望' },
  { word: 'appliance', phonetic: '/əˈplaɪəns/', meaning: 'n. 器具；设备' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', meaning: 'n. 申请；应用' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: 'v. 任命；约定' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: 'v. 欣赏；感激' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: 'v. 接近 n. 方法' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: 'adj. 适当的；恰当的' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准；赞成' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现；产生' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排；整理' },
  { word: 'artificial', phonetic: '/ˌɑːtɪˈfɪʃl/', meaning: 'adj. 人工的；虚假的' },
  { word: 'assess', phonetic: '/əˈses/', meaning: 'v. 评估；评定' },
  { word: 'assign', phonetic: '/əˈsaɪn/', meaning: 'v. 分配；指派' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 帮助；协助' },
  { word: 'associate', phonetic: '/əˈsəʊʃieɪt/', meaning: 'v. 联系；联想' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: 'v. 假定；承担' },
  { word: 'assure', phonetic: '/əˈʃʊər/', meaning: 'v. 保证；使确信' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', meaning: 'n. 大气层；氛围' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附上；依恋' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: 'v. 达到；获得' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'v./n. 尝试；企图' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: 'n. 态度；看法' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引' },
  { word: 'authority', phonetic: '/ɔːˈθɒrəti/', meaning: 'n. 权威；当局' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', meaning: 'adj. 自动的' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的；可得到的' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'adj. 平均的 n. 平均数' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免；回避' },
  { word: 'aware', phonetic: '/əˈweər/', meaning: 'adj. 意识到的' },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: 'n. 平衡 v. 使平衡' },
  { word: 'barrier', phonetic: '/ˈbæriər/', meaning: 'n. 障碍；屏障' },
  { word: 'behalf', phonetic: '/bɪˈhɑːf/', meaning: 'n. 利益；代表' },
  { word: 'behave', phonetic: '/bɪˈheɪv/', meaning: 'v. 表现；行为' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: 'n. 利益 v. 有益于' },
  { word: 'beyond', phonetic: '/bɪˈjɒnd/', meaning: 'prep. 超越；在…之外' },
  { word: 'blame', phonetic: '/bleɪm/', meaning: 'v. 责备 n. 过失' },
  { word: 'boom', phonetic: '/buːm/', meaning: 'n./v. 繁荣；激增' },
  { word: 'boost', phonetic: '/buːst/', meaning: 'v. 促进；增加' },
  { word: 'boundary', phonetic: '/ˈbaʊndri/', meaning: 'n. 边界；界限' },
  { word: 'breakthrough', phonetic: '/ˈbreɪkθruː/', meaning: 'n. 突破' },
  { word: 'brief', phonetic: '/briːf/', meaning: 'adj. 简短的 v. 汇报' },
  { word: 'brilliant', phonetic: '/ˈbrɪliənt/', meaning: 'adj. 杰出的；辉煌的' },
  { word: 'burden', phonetic: '/ˈbɜːrdn/', meaning: 'n. 负担 v. 使负重' },
  { word: 'calculate', phonetic: '/ˈkælkjuleɪt/', meaning: 'v. 计算' },
  { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'n. 运动；战役' },
  { word: 'candidate', phonetic: '/ˈkændɪdət/', meaning: 'n. 候选人' },
  { word: 'capable', phonetic: '/ˈkeɪpəbl/', meaning: 'adj. 有能力的' },
  { word: 'capacity', phonetic: '/kəˈpæsəti/', meaning: 'n. 容量；能力' },
  { word: 'capture', phonetic: '/ˈkæptʃər/', meaning: 'v. 捕获；夺取' },
  { word: 'career', phonetic: '/kəˈrɪər/', meaning: 'n. 职业；事业' },
  { word: 'casual', phonetic: '/ˈkæʒuəl/', meaning: 'adj. 随意的；非正式的' },
  { word: 'category', phonetic: '/ˈkætəɡəri/', meaning: 'n. 类别；种类' },
  { word: 'cautious', phonetic: '/ˈkɔːʃəs/', meaning: 'adj. 谨慎的' },
  { word: 'cease', phonetic: '/siːs/', meaning: 'v. 停止；终止' },
  { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: 'n./v. 挑战' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: 'n. 冠军；拥护者' },
  { word: 'characteristic', phonetic: '/ˌkærəktəˈrɪstɪk/', meaning: 'n. 特征 adj. 特有的' },
  { word: 'circumstance', phonetic: '/ˈsɜːrkəmstəns/', meaning: 'n. 环境；情况' },
  { word: 'civilization', phonetic: '/ˌsɪvəlaɪˈzeɪʃn/', meaning: 'n. 文明' },
  { word: 'classify', phonetic: '/ˈklæsɪfaɪ/', meaning: 'v. 分类' },
  { word: 'climate', phonetic: '/ˈklaɪmət/', meaning: 'n. 气候' },
  { word: 'coincidence', phonetic: '/kəʊˈɪnsɪdəns/', meaning: 'n. 巧合' },
  { word: 'collapse', phonetic: '/kəˈlæps/', meaning: 'v./n. 倒塌；崩溃' },
  { word: 'colleague', phonetic: '/ˈkɒliːɡ/', meaning: 'n. 同事' },
  { word: 'combination', phonetic: '/ˌkɒmbɪˈneɪʃn/', meaning: 'n. 结合；组合' },
  { word: 'command', phonetic: '/kəˈmɑːnd/', meaning: 'v./n. 命令；掌握' },
  { word: 'comment', phonetic: '/ˈkɒment/', meaning: 'n./v. 评论' },
  { word: 'commit', phonetic: '/kəˈmɪt/', meaning: 'v. 犯(罪)；承诺' },
  { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: 'v. 交流；传达' },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: 'n. 社区；团体' },
  { word: 'companion', phonetic: '/kəmˈpæniən/', meaning: 'n. 同伴；伙伴' },
  { word: 'compare', phonetic: '/kəmˈpeər/', meaning: 'v. 比较；对比' },
  { word: 'compel', phonetic: '/kəmˈpel/', meaning: 'v. 强迫；迫使' },
  { word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', meaning: 'v. 补偿；赔偿' },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争；比赛' },
  { word: 'competent', phonetic: '/ˈkɒmpɪtənt/', meaning: 'adj. 有能力的；胜任的' },
  { word: 'complaint', phonetic: '/kəmˈpleɪnt/', meaning: 'n. 投诉；抱怨' },
  { word: 'complex', phonetic: '/ˈkɒmpleks/', meaning: 'adj. 复杂的 n. 综合体' },
  { word: 'component', phonetic: '/kəmˈpəʊnənt/', meaning: 'n. 成分；组件' },
  { word: 'compose', phonetic: '/kəmˈpəʊz/', meaning: 'v. 组成；创作' },
  { word: 'comprehension', phonetic: '/ˌkɒmprɪˈhenʃn/', meaning: 'n. 理解；理解力' },
  { word: 'compromise', phonetic: '/ˈkɒmprəmaɪz/', meaning: 'n./v. 妥协' },
  { word: 'concentrate', phonetic: '/ˈkɒnsntreɪt/', meaning: 'v. 集中；专心' },
  { word: 'concept', phonetic: '/ˈkɒnsept/', meaning: 'n. 概念；观念' },
  { word: 'concern', phonetic: '/kənˈsɜːrn/', meaning: 'v. 涉及 n. 关心；忧虑' },
  { word: 'conclude', phonetic: '/kənˈkluːd/', meaning: 'v. 得出结论；结束' },
  { word: 'concrete', phonetic: '/ˈkɒŋkriːt/', meaning: 'adj. 具体的 n. 混凝土' },
  { word: 'conduct', phonetic: '/kənˈdʌkt/', meaning: 'v. 实施；指挥 n. 行为' },
  { word: 'conference', phonetic: '/ˈkɒnfərəns/', meaning: 'n. 会议' },
  { word: 'confidence', phonetic: '/ˈkɒnfɪdəns/', meaning: 'n. 信心；自信' },
  { word: 'confirm', phonetic: '/kənˈfɜːrm/', meaning: 'v. 证实；确认' },
  { word: 'conflict', phonetic: '/ˈkɒnflɪkt/', meaning: 'n. 冲突；矛盾' },
  { word: 'confuse', phonetic: '/kənˈfjuːz/', meaning: 'v. 使困惑；混淆' },
  { word: 'congratulate', phonetic: '/kənˈɡrætʃuleɪt/', meaning: 'v. 祝贺' },
  { word: 'connect', phonetic: '/kəˈnekt/', meaning: 'v. 连接；联系' },
  { word: 'conscience', phonetic: '/ˈkɒnʃəns/', meaning: 'n. 良心；道德感' },
  { word: 'conscious', phonetic: '/ˈkɒnʃəs/', meaning: 'adj. 意识到的；有意的' },
  { word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', meaning: 'n. 结果；后果' },
  { word: 'conservation', phonetic: '/ˌkɒnsərˈveɪʃn/', meaning: 'n. 保护；保存' },
  { word: 'conservative', phonetic: '/kənˈsɜːrvətɪv/', meaning: 'adj. 保守的 n. 保守派' },
  { word: 'consider', phonetic: '/kənˈsɪdər/', meaning: 'v. 考虑；认为' },
  { word: 'consist', phonetic: '/kənˈsɪst/', meaning: 'v. 由…组成；在于' },
  { word: 'constant', phonetic: '/ˈkɒnstənt/', meaning: 'adj. 不断的；恒定的' },
  { word: 'constitute', phonetic: '/ˈkɒnstɪtjuːt/', meaning: 'v. 构成；组成' },
  { word: 'construct', phonetic: '/kənˈstrʌkt/', meaning: 'v. 建造；构建' },
  { word: 'consult', phonetic: '/kənˈsʌlt/', meaning: 'v. 咨询；查阅' },
  { word: 'consume', phonetic: '/kənˈsjuːm/', meaning: 'v. 消耗；消费' },
  { word: 'contact', phonetic: '/ˈkɒntækt/', meaning: 'n./v. 接触；联系' },
  { word: 'contain', phonetic: '/kənˈteɪn/', meaning: 'v. 包含；容纳' },
  { word: 'contemporary', phonetic: '/kənˈtempəreri/', meaning: 'adj. 当代的 n. 同代人' },
  { word: 'content', phonetic: '/ˈkɒntent/', meaning: 'n. 内容 adj. 满足的' },
  { word: 'context', phonetic: '/ˈkɒntekst/', meaning: 'n. 上下文；背景' },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: 'v. 继续；延续' },
  { word: 'contradict', phonetic: '/ˌkɒntrəˈdɪkt/', meaning: 'v. 反驳；矛盾' },
  { word: 'contrary', phonetic: '/ˈkɒntrəri/', meaning: 'adj. 相反的 n. 反面' },
  { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: 'v. 贡献；捐献' },
  { word: 'controversial', phonetic: '/ˌkɒntrəˈvɜːrʃl/', meaning: 'adj. 有争议的' },
  { word: 'convenience', phonetic: '/kənˈviːniəns/', meaning: 'n. 便利；方便' },
  { word: 'conventional', phonetic: '/kənˈvenʃənl/', meaning: 'adj. 传统的；常规的' },
  { word: 'convince', phonetic: '/kənˈvɪns/', meaning: 'v. 使确信；说服' },
  { word: 'cooperate', phonetic: '/kəʊˈɒpəreɪt/', meaning: 'v. 合作；协作' },
  { word: 'correspond', phonetic: '/ˌkɒrɪˈspɒnd/', meaning: 'v. 相符；通信' },
  { word: 'corrupt', phonetic: '/kəˈrʌpt/', meaning: 'adj. 腐败的 v. 使堕落' },
  { word: 'council', phonetic: '/ˈkaʊnsl/', meaning: 'n. 委员会；议会' },
  { word: 'courage', phonetic: '/ˈkʌrɪdʒ/', meaning: 'n. 勇气；胆量' },
  { word: 'crash', phonetic: '/kræʃ/', meaning: 'v./n. 碰撞；崩溃' },
  { word: 'creative', phonetic: '/kriˈeɪtɪv/', meaning: 'adj. 创造性的' },
  { word: 'crisis', phonetic: '/ˈkraɪsɪs/', meaning: 'n. 危机' },
  { word: 'criterion', phonetic: '/kraɪˈtɪəriən/', meaning: 'n. 标准；准则' },
  { word: 'crucial', phonetic: '/ˈkruːʃl/', meaning: 'adj. 关键的；决定性的' },
  { word: 'cultivate', phonetic: '/ˈkʌltɪveɪt/', meaning: 'v. 培养；耕作' },
  { word: 'curiosity', phonetic: '/ˌkjʊəriˈɒsəti/', meaning: 'n. 好奇心' },
  { word: 'currency', phonetic: '/ˈkʌrənsi/', meaning: 'n. 货币；通货' },
  { word: 'current', phonetic: '/ˈkʌrənt/', meaning: 'adj. 当前的 n. 水流；电流' },
  { word: 'curriculum', phonetic: '/kəˈrɪkjələm/', meaning: 'n. 课程' },
  { word: 'custom', phonetic: '/ˈkʌstəm/', meaning: 'n. 习俗；风俗' },
  { word: 'deadline', phonetic: '/ˈdedlaɪn/', meaning: 'n. 截止日期' },
  { word: 'debate', phonetic: '/dɪˈbeɪt/', meaning: 'n./v. 辩论；争论' },
  { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: 'n. 十年' },
  { word: 'declare', phonetic: '/dɪˈkleər/', meaning: 'v. 宣布；声明' },
  { word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: 'v. 下降；拒绝' },
  { word: 'decorate', phonetic: '/ˈdekəreɪt/', meaning: 'v. 装饰' },
  { word: 'decrease', phonetic: '/dɪˈkriːs/', meaning: 'v./n. 减少' },
  { word: 'dedicate', phonetic: '/ˈdedɪkeɪt/', meaning: 'v. 致力于；奉献' },
  { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: 'v./n. 击败；失败' },
  { word: 'defend', phonetic: '/dɪˈfend/', meaning: 'v. 防御；辩护' },
  { word: 'define', phonetic: '/dɪˈfaɪn/', meaning: 'v. 定义；界定' },
  { word: 'definite', phonetic: '/ˈdefɪnət/', meaning: 'adj. 明确的；确定的' },
  { word: 'delay', phonetic: '/dɪˈleɪ/', meaning: 'v./n. 推迟；延误' },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', meaning: 'adj. 故意的 v. 仔细考虑' },
  { word: 'delicate', phonetic: '/ˈdelɪkət/', meaning: 'adj. 精美的；微妙的' },
  { word: 'deliver', phonetic: '/dɪˈlɪvər/', meaning: 'v. 递送；发表' },
  { word: 'demand', phonetic: '/dɪˈmɑːnd/', meaning: 'v./n. 要求；需求' },
  { word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', meaning: 'v. 证明；演示' },
  { word: 'deny', phonetic: '/dɪˈnaɪ/', meaning: 'v. 否认；拒绝' },
  { word: 'depart', phonetic: '/dɪˈpɑːrt/', meaning: 'v. 出发；离开' },
  { word: 'depend', phonetic: '/dɪˈpend/', meaning: 'v. 依赖；取决于' },
  { word: 'deposit', phonetic: '/dɪˈpɒzɪt/', meaning: 'n. 存款 v. 存放' },
  { word: 'depress', phonetic: '/dɪˈpres/', meaning: 'v. 使沮丧；使萧条' },
  { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: 'v. 源于；获得' },
  { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning: 'v. 描述；描写' },
  { word: 'deserve', phonetic: '/dɪˈzɜːrv/', meaning: 'v. 值得；应受' },
  { word: 'design', phonetic: '/dɪˈzaɪn/', meaning: 'v./n. 设计' },
  { word: 'desperate', phonetic: '/ˈdespərət/', meaning: 'adj. 绝望的；拼命的' },
  { word: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', meaning: 'n. 目的地' },
  { word: 'destroy', phonetic: '/dɪˈstrɔɪ/', meaning: 'v. 破坏；毁灭' },
  { word: 'determine', phonetic: '/dɪˈtɜːrmɪn/', meaning: 'v. 决定；确定' },
  { word: 'develop', phonetic: '/dɪˈveləp/', meaning: 'v. 发展；开发' },
  { word: 'device', phonetic: '/dɪˈvaɪs/', meaning: 'n. 设备；装置' },
  { word: 'devote', phonetic: '/dɪˈvəʊt/', meaning: 'v. 奉献；致力于' },
  { word: 'diagnose', phonetic: '/ˈdaɪəɡnəʊz/', meaning: 'v. 诊断' },
  { word: 'dictate', phonetic: '/dɪkˈteɪt/', meaning: 'v. 口述；命令' },
  { word: 'differ', phonetic: '/ˈdɪfər/', meaning: 'v. 不同；有区别' },
  { word: 'digest', phonetic: '/daɪˈdʒest/', meaning: 'v. 消化；领悟' },
  { word: 'dilemma', phonetic: '/dɪˈlemə/', meaning: 'n. 困境；两难' },
  { word: 'dimension', phonetic: '/daɪˈmenʃn/', meaning: 'n. 维度；方面' },
  { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', meaning: 'v. 减少；缩小' },
  { word: 'discipline', phonetic: '/ˈdɪsəplɪn/', meaning: 'n. 纪律；学科' },
  { word: 'discount', phonetic: '/ˈdɪskaʊnt/', meaning: 'n. 折扣' },
  { word: 'discover', phonetic: '/dɪˈskʌvər/', meaning: 'v. 发现' },
  { word: 'discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃn/', meaning: 'n. 歧视；辨别力' },
  { word: 'disguise', phonetic: '/dɪsˈɡaɪz/', meaning: 'v./n. 伪装；假扮' },
  { word: 'dismiss', phonetic: '/dɪsˈmɪs/', meaning: 'v. 解雇；驳回' },
  { word: 'display', phonetic: '/dɪˈspleɪ/', meaning: 'v./n. 展示；陈列' },
  { word: 'dispose', phonetic: '/dɪˈspəʊz/', meaning: 'v. 处理；安排' },
  { word: 'dispute', phonetic: '/dɪˈspjuːt/', meaning: 'n./v. 争论；纠纷' },
  { word: 'distinct', phonetic: '/dɪˈstɪŋkt/', meaning: 'adj. 明显的；独特的' },
  { word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/', meaning: 'v. 区分；辨别' },
  { word: 'distribute', phonetic: '/dɪˈstrɪbjuːt/', meaning: 'v. 分配；分发' },
  { word: 'disturb', phonetic: '/dɪˈstɜːrb/', meaning: 'v. 打扰；扰乱' },
  { word: 'diverse', phonetic: '/daɪˈvɜːrs/', meaning: 'adj. 多样的；不同的' },
  { word: 'divorce', phonetic: '/dɪˈvɔːrs/', meaning: 'n./v. 离婚' },
  { word: 'domestic', phonetic: '/dəˈmestɪk/', meaning: 'adj. 国内的；家庭的' },
  { word: 'dominant', phonetic: '/ˈdɒmɪnənt/', meaning: 'adj. 占主导地位的' },
  { word: 'dominate', phonetic: '/ˈdɒmɪneɪt/', meaning: 'v. 支配；控制' },
  { word: 'donate', phonetic: '/dəʊˈneɪt/', meaning: 'v. 捐赠' },
  { word: 'dramatic', phonetic: '/drəˈmætɪk/', meaning: 'adj. 戏剧性的；巨大的' },
  { word: 'durable', phonetic: '/ˈdjʊərəbl/', meaning: 'adj. 耐用的；持久的' },
  { word: 'dynamic', phonetic: '/daɪˈnæmɪk/', meaning: 'adj. 动态的；充满活力的' },
  { word: 'eager', phonetic: '/ˈiːɡər/', meaning: 'adj. 渴望的；热切的' },
  { word: 'economy', phonetic: '/ɪˈkɒnəmi/', meaning: 'n. 经济' },
  { word: 'edit', phonetic: '/ˈedɪt/', meaning: 'v. 编辑' },
  { word: 'effect', phonetic: '/ɪˈfekt/', meaning: 'n. 效果；影响' },
  { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: 'adj. 高效的' },
  { word: 'elaborate', phonetic: '/ɪˈlæbərət/', meaning: 'adj. 精心的 v. 详细说明' },
  { word: 'elect', phonetic: '/ɪˈlekt/', meaning: 'v. 选举；选择' },
  { word: 'elegant', phonetic: '/ˈelɪɡənt/', meaning: 'adj. 优雅的' },
  { word: 'element', phonetic: '/ˈelɪmənt/', meaning: 'n. 元素；要素' },
  { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning: 'v. 消除；淘汰' },
  { word: 'embrace', phonetic: '/ɪmˈbreɪs/', meaning: 'v. 拥抱；接受' },
  { word: 'emerge', phonetic: '/ɪˈmɜːrdʒ/', meaning: 'v. 出现；浮现' },
  { word: 'emotion', phonetic: '/ɪˈməʊʃn/', meaning: 'n. 情感；情绪' },
  { word: 'emphasize', phonetic: '/ˈemfəsaɪz/', meaning: 'v. 强调' },
  { word: 'employ', phonetic: '/ɪmˈplɔɪ/', meaning: 'v. 雇佣；使用' },
  { word: 'enable', phonetic: '/ɪˈneɪbl/', meaning: 'v. 使能够' },
  { word: 'encounter', phonetic: '/ɪnˈkaʊntər/', meaning: 'v./n. 遭遇；邂逅' },
  { word: 'encourage', phonetic: '/ɪnˈkʌrɪdʒ/', meaning: 'v. 鼓励' },
  { word: 'endure', phonetic: '/ɪnˈdjʊər/', meaning: 'v. 忍受；持久' },
  { word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', meaning: 'v. 从事；吸引' },
  { word: 'enhance', phonetic: '/ɪnˈhɑːns/', meaning: 'v. 增强；提高' },
  { word: 'enormous', phonetic: '/ɪˈnɔːrməs/', meaning: 'adj. 巨大的' },
  { word: 'ensure', phonetic: '/ɪnˈʃʊər/', meaning: 'v. 确保' },
  { word: 'enterprise', phonetic: '/ˈentəpraɪz/', meaning: 'n. 企业；事业' },
  { word: 'enthusiasm', phonetic: '/ɪnˈθjuːziæzəm/', meaning: 'n. 热情；热忱' },
  { word: 'entire', phonetic: '/ɪnˈtaɪər/', meaning: 'adj. 全部的；整个的' },
  { word: 'entry', phonetic: '/ˈentri/', meaning: 'n. 进入；入口；条目' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: 'n. 环境' },
  { word: 'episode', phonetic: '/ˈepɪsəʊd/', meaning: 'n. 一集；一段经历' },
  { word: 'equality', phonetic: '/ɪˈkwɒləti/', meaning: 'n. 平等' },
  { word: 'equip', phonetic: '/ɪˈkwɪp/', meaning: 'v. 装备；配备' },
  { word: 'equivalent', phonetic: '/ɪˈkwɪvələnt/', meaning: 'adj. 等价的 n. 等价物' },
  { word: 'escape', phonetic: '/ɪˈskeɪp/', meaning: 'v./n. 逃跑；逃脱' },
  { word: 'essential', phonetic: '/ɪˈsenʃl/', meaning: 'adj. 必要的；本质的' },
  { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: 'v. 建立；确立' },
  { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: 'v./n. 估计' },
  { word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: 'v. 评估；评价' },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: 'n. 证据' },
  { word: 'evident', phonetic: '/ˈevɪdənt/', meaning: 'adj. 明显的' },
  { word: 'evolution', phonetic: '/ˌiːvəˈluːʃn/', meaning: 'n. 进化；演变' },
  { word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', meaning: 'v. 夸张；夸大' },
  { word: 'examine', phonetic: '/ɪɡˈzæmɪn/', meaning: 'v. 检查；考试' },
  { word: 'exceed', phonetic: '/ɪkˈsiːd/', meaning: 'v. 超过；超出' },
  { word: 'exception', phonetic: '/ɪkˈsepʃn/', meaning: 'n. 例外' },
  { word: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', meaning: 'v./n. 交换；兑换' },
  { word: 'exclaim', phonetic: '/ɪkˈskleɪm/', meaning: 'v. 惊叫；呼喊' },
  { word: 'exclude', phonetic: '/ɪkˈskluːd/', meaning: 'v. 排除；排斥' },
  { word: 'execute', phonetic: '/ˈeksɪkjuːt/', meaning: 'v. 执行；处决' },
  { word: 'exhibit', phonetic: '/ɪɡˈzɪbɪt/', meaning: 'v. 展览 n. 展品' },
  { word: 'exist', phonetic: '/ɪɡˈzɪst/', meaning: 'v. 存在' },
  { word: 'expand', phonetic: '/ɪkˈspænd/', meaning: 'v. 扩展；膨胀' },
  { word: 'expect', phonetic: '/ɪkˈspekt/', meaning: 'v. 期望；预期' },
  { word: 'expedition', phonetic: '/ˌekspəˈdɪʃn/', meaning: 'n. 远征；探险' },
  { word: 'expense', phonetic: '/ɪkˈspens/', meaning: 'n. 费用；开支' },
  { word: 'experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: 'n. 实验' },
  { word: 'expert', phonetic: '/ˈekspɜːrt/', meaning: 'n. 专家' },
  { word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', meaning: 'v. 开发；利用' },
  { word: 'explore', phonetic: '/ɪkˈsplɔːr/', meaning: 'v. 探索；探究' },
  { word: 'expose', phonetic: '/ɪkˈspəʊz/', meaning: 'v. 暴露；揭露' },
  { word: 'extension', phonetic: '/ɪkˈstenʃn/', meaning: 'n. 延伸；扩展' },
  { word: 'extent', phonetic: '/ɪkˈstent/', meaning: 'n. 程度；范围' },
  { word: 'external', phonetic: '/ɪkˈstɜːrnl/', meaning: 'adj. 外部的；外界的' },
  { word: 'extinct', phonetic: '/ɪkˈstɪŋkt/', meaning: 'adj. 灭绝的' },
  { word: 'extraordinary', phonetic: '/ɪkˈstrɔːrdnri/', meaning: 'adj. 非凡的；特别的' },
  { word: 'extreme', phonetic: '/ɪkˈstriːm/', meaning: 'adj. 极端的 n. 极端' },
  { word: 'facility', phonetic: '/fəˈsɪləti/', meaning: 'n. 设施；设备' },
  { word: 'failure', phonetic: '/ˈfeɪljər/', meaning: 'n. 失败；故障' },
  { word: 'faithful', phonetic: '/ˈfeɪθfl/', meaning: 'adj. 忠实的；忠诚的' },
  { word: 'familiar', phonetic: '/fəˈmɪliər/', meaning: 'adj. 熟悉的' },
  { word: 'fantastic', phonetic: '/fænˈtæstɪk/', meaning: 'adj. 极好的；奇异的' },
  { word: 'fascinate', phonetic: '/ˈfæsɪneɪt/', meaning: 'v. 使着迷' },
  { word: 'fate', phonetic: '/feɪt/', meaning: 'n. 命运' },
  { word: 'feature', phonetic: '/ˈfiːtʃər/', meaning: 'n. 特征；特色' },
  { word: 'fellow', phonetic: '/ˈfeləʊ/', meaning: 'n. 家伙；同伴' },
  { word: 'fiction', phonetic: '/ˈfɪkʃn/', meaning: 'n. 小说；虚构' },
  { word: 'figure', phonetic: '/ˈfɪɡər/', meaning: 'n. 数字；人物 v. 理解' },
  { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning: 'n. 财政；金融' },
  { word: 'flexible', phonetic: '/ˈfleksəbl/', meaning: 'adj. 灵活的；可弯曲的' },
  { word: 'fluent', phonetic: '/ˈfluːənt/', meaning: 'adj. 流利的' },
  { word: 'forbid', phonetic: '/fərˈbɪd/', meaning: 'v. 禁止' },
  { word: 'forecast', phonetic: '/ˈfɔːrkɑːst/', meaning: 'v./n. 预测；预报' },
  { word: 'forgive', phonetic: '/fərˈɡɪv/', meaning: 'v. 原谅；宽恕' },
  { word: 'formal', phonetic: '/ˈfɔːrml/', meaning: 'adj. 正式的；形式的' },
  { word: 'former', phonetic: '/ˈfɔːrmər/', meaning: 'adj. 前者的 n. 前者' },
  { word: 'formula', phonetic: '/ˈfɔːrmjələ/', meaning: 'n. 公式；配方' },
  { word: 'fortune', phonetic: '/ˈfɔːrtʃuːn/', meaning: 'n. 运气；财富' },
  { word: 'foundation', phonetic: '/faʊnˈdeɪʃn/', meaning: 'n. 基础；基金会' },
  { word: 'fraction', phonetic: '/ˈfrækʃn/', meaning: 'n. 分数；小部分' },
  { word: 'fragment', phonetic: '/ˈfræɡmənt/', meaning: 'n. 碎片；片段' },
  { word: 'framework', phonetic: '/ˈfreɪmwɜːrk/', meaning: 'n. 框架；体制' },
  { word: 'frequency', phonetic: '/ˈfriːkwənsi/', meaning: 'n. 频率；频繁' },
  { word: 'friction', phonetic: '/ˈfrɪkʃn/', meaning: 'n. 摩擦；冲突' },
  { word: 'frontier', phonetic: '/ˈfrʌntɪər/', meaning: 'n. 边界；前沿' },
  { word: 'frustrate', phonetic: '/frʌˈstreɪt/', meaning: 'v. 使沮丧；挫败' },
  { word: 'fulfill', phonetic: '/fʊlˈfɪl/', meaning: 'v. 实现；履行' },
  { word: 'function', phonetic: '/ˈfʌŋkʃn/', meaning: 'n. 功能 v. 运作' },
  { word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: 'adj. 基本的；根本的' },
  { word: 'furnish', phonetic: '/ˈfɜːrnɪʃ/', meaning: 'v. 装修；提供' },
  { word: 'gallery', phonetic: '/ˈɡæləri/', meaning: 'n. 画廊；走廊' },
  { word: 'gap', phonetic: '/ɡæp/', meaning: 'n. 差距；缺口' },
  { word: 'gather', phonetic: '/ˈɡæðər/', meaning: 'v. 聚集；收集' },
  { word: 'generate', phonetic: '/ˈdʒenəreɪt/', meaning: 'v. 产生；发电' },
  { word: 'generous', phonetic: '/ˈdʒenərəs/', meaning: 'adj. 慷慨的；大量的' },
  { word: 'genuine', phonetic: '/ˈdʒenjuɪn/', meaning: 'adj. 真正的；真诚的' },
  { word: 'gesture', phonetic: '/ˈdʒestʃər/', meaning: 'n. 手势；姿态' },
  { word: 'global', phonetic: '/ˈɡləʊbl/', meaning: 'adj. 全球的' },
  { word: 'gloomy', phonetic: '/ˈɡluːmi/', meaning: 'adj. 阴暗的；沮丧的' },
  { word: 'govern', phonetic: '/ˈɡʌvərn/', meaning: 'v. 统治；管理' },
  { word: 'gradual', phonetic: '/ˈɡrædʒuəl/', meaning: 'adj. 逐渐的' },
  { word: 'grant', phonetic: '/ɡrɑːnt/', meaning: 'v. 授予；同意 n. 拨款' },
  { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: 'v./n. 保证；担保' },
  { word: 'guilty', phonetic: '/ˈɡɪlti/', meaning: 'adj. 有罪的；内疚的' },
  { word: 'harmony', phonetic: '/ˈhɑːrməni/', meaning: 'n. 和谐；协调' },
  { word: 'harvest', phonetic: '/ˈhɑːrvɪst/', meaning: 'n./v. 收获；收割' },
  { word: 'hesitate', phonetic: '/ˈhezɪteɪt/', meaning: 'v. 犹豫；踌躇' },
  { word: 'highlight', phonetic: '/ˈhaɪlaɪt/', meaning: 'v. 强调 n. 亮点' },
  { word: 'hinder', phonetic: '/ˈhɪndər/', meaning: 'v. 阻碍；妨碍' },
  { word: 'horizon', phonetic: '/həˈraɪzn/', meaning: 'n. 地平线；视野' },
  { word: 'hostile', phonetic: '/ˈhɒstaɪl/', meaning: 'adj. 敌意的；不友好的' },
  { word: 'humble', phonetic: '/ˈhʌmbl/', meaning: 'adj. 谦虚的；卑微的' },
  { word: 'identical', phonetic: '/aɪˈdentɪkl/', meaning: 'adj. 完全相同的' },
  { word: 'identify', phonetic: '/aɪˈdentɪfaɪ/', meaning: 'v. 识别；确认' },
  { word: 'ignorance', phonetic: '/ˈɪɡnərəns/', meaning: 'n. 无知；愚昧' },
  { word: 'illustrate', phonetic: '/ˈɪləstreɪt/', meaning: 'v. 说明；图解' },
  { word: 'imaginary', phonetic: '/ɪˈmædʒɪnəri/', meaning: 'adj. 想象的；虚构的' },
  { word: 'immediate', phonetic: '/ɪˈmiːdiət/', meaning: 'adj. 立即的；直接的' },
  { word: 'immigrate', phonetic: '/ˈɪmɪɡreɪt/', meaning: 'v. 移民' },
  { word: 'impact', phonetic: '/ˈɪmpækt/', meaning: 'n./v. 影响；冲击' },
  { word: 'implement', phonetic: '/ˈɪmplɪment/', meaning: 'v. 实施 n. 工具' },
  { word: 'imply', phonetic: '/ɪmˈplaɪ/', meaning: 'v. 暗示；意味着' },
  { word: 'impose', phonetic: '/ɪmˈpəʊz/', meaning: 'v. 强加；征收' },
  { word: 'impress', phonetic: '/ɪmˈpres/', meaning: 'v. 给…留下深刻印象' },
  { word: 'impulse', phonetic: '/ˈɪmpʌls/', meaning: 'n. 冲动；脉冲' },
  { word: 'incident', phonetic: '/ˈɪnsɪdənt/', meaning: 'n. 事件；事变' },
  { word: 'incredible', phonetic: '/ɪnˈkredəbl/', meaning: 'adj. 难以置信的' },
  { word: 'independence', phonetic: '/ˌɪndɪˈpendəns/', meaning: 'n. 独立' },
  { word: 'indicate', phonetic: '/ˈɪndɪkeɪt/', meaning: 'v. 表明；指出' },
  { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning: 'adj. 个人的 n. 个人' },
  { word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', meaning: 'adj. 不可避免的' },
  { word: 'influence', phonetic: '/ˈɪnfluəns/', meaning: 'n./v. 影响' },
  { word: 'inform', phonetic: '/ɪnˈfɔːrm/', meaning: 'v. 通知；告知' },
  { word: 'ingredient', phonetic: '/ɪnˈɡriːdiənt/', meaning: 'n. 成分；要素' },
  { word: 'initial', phonetic: '/ɪˈnɪʃl/', meaning: 'adj. 最初的 n. 首字母' },
  { word: 'initiative', phonetic: '/ɪˈnɪʃətɪv/', meaning: 'n. 主动性；倡议' },
  { word: 'innocent', phonetic: '/ˈɪnəsnt/', meaning: 'adj. 无辜的；天真的' },
  { word: 'innovation', phonetic: '/ˌɪnəˈveɪʃn/', meaning: 'n. 创新' },
  { word: 'inquire', phonetic: '/ɪnˈkwaɪər/', meaning: 'v. 询问；调查' },
  { word: 'insert', phonetic: '/ɪnˈsɜːrt/', meaning: 'v. 插入；嵌入' },
  { word: 'insight', phonetic: '/ˈɪnsaɪt/', meaning: 'n. 洞察力；见解' },
  { word: 'insist', phonetic: '/ɪnˈsɪst/', meaning: 'v. 坚持；坚决要求' },
  { word: 'inspect', phonetic: '/ɪnˈspekt/', meaning: 'v. 检查；视察' },
  { word: 'inspire', phonetic: '/ɪnˈspaɪər/', meaning: 'v. 激励；启发' },
  { word: 'install', phonetic: '/ɪnˈstɔːl/', meaning: 'v. 安装' },
  { word: 'instance', phonetic: '/ˈɪnstəns/', meaning: 'n. 例子；实例' },
  { word: 'instinct', phonetic: '/ˈɪnstɪŋkt/', meaning: 'n. 本能；直觉' },
  { word: 'institute', phonetic: '/ˈɪnstɪtjuːt/', meaning: 'n. 学院；研究所' },
  { word: 'instruct', phonetic: '/ɪnˈstrʌkt/', meaning: 'v. 指导；指示' },
  { word: 'insure', phonetic: '/ɪnˈʃʊər/', meaning: 'v. 保险；确保' },
  { word: 'integrate', phonetic: '/ˈɪntɪɡreɪt/', meaning: 'v. 整合；融入' },
  { word: 'intellectual', phonetic: '/ˌɪntəˈlektʃuəl/', meaning: 'adj. 智力的 n. 知识分子' },
  { word: 'intelligent', phonetic: '/ɪnˈtelɪdʒənt/', meaning: 'adj. 聪明的' },
  { word: 'intend', phonetic: '/ɪnˈtend/', meaning: 'v. 打算；想要' },
  { word: 'intense', phonetic: '/ɪnˈtens/', meaning: 'adj. 强烈的；紧张的' },
  { word: 'intention', phonetic: '/ɪnˈtenʃn/', meaning: 'n. 意图；目的' },
  { word: 'interact', phonetic: '/ˌɪntərˈækt/', meaning: 'v. 互动；交流' },
  { word: 'interfere', phonetic: '/ˌɪntərˈfɪər/', meaning: 'v. 干涉；妨碍' },
  { word: 'interpret', phonetic: '/ɪnˈtɜːrprɪt/', meaning: 'v. 解释；口译' },
  { word: 'interrupt', phonetic: '/ˌɪntəˈrʌpt/', meaning: 'v. 打断；中断' },
  { word: 'interval', phonetic: '/ˈɪntərvl/', meaning: 'n. 间隔；间歇' },
  { word: 'intimate', phonetic: '/ˈɪntɪmət/', meaning: 'adj. 亲密的 n. 知己' },
  { word: 'invade', phonetic: '/ɪnˈveɪd/', meaning: 'v. 入侵；侵略' },
  { word: 'invest', phonetic: '/ɪnˈvest/', meaning: 'v. 投资' },
  { word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', meaning: 'v. 调查；研究' },
  { word: 'invisible', phonetic: '/ɪnˈvɪzəbl/', meaning: 'adj. 看不见的' },
  { word: 'involve', phonetic: '/ɪnˈvɒlv/', meaning: 'v. 涉及；包含' },
  { word: 'isolate', phonetic: '/ˈaɪsəleɪt/', meaning: 'v. 隔离；孤立' },
  { word: 'issue', phonetic: '/ˈɪʃuː/', meaning: 'n. 问题；发行 v. 发布' },
  { word: 'justify', phonetic: '/ˈdʒʌstɪfaɪ/', meaning: 'v. 证明…正当；为…辩护' },
  { word: 'keen', phonetic: '/kiːn/', meaning: 'adj. 渴望的；敏锐的' },
  { word: 'labor', phonetic: '/ˈleɪbər/', meaning: 'n. 劳动；劳工' },
  { word: 'launch', phonetic: '/lɔːntʃ/', meaning: 'v. 发射；发起 n. 发射' },
  { word: 'layer', phonetic: '/ˈleɪər/', meaning: 'n. 层；阶层' },
  { word: 'lean', phonetic: '/liːn/', meaning: 'v. 倾斜；倚靠 adj. 瘦的' },
  { word: 'legal', phonetic: '/ˈliːɡl/', meaning: 'adj. 合法的；法律的' },
  { word: 'legend', phonetic: '/ˈledʒənd/', meaning: 'n. 传说；传奇' },
  { word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', meaning: 'adj. 合法的；正当的' },
  { word: 'leisure', phonetic: '/ˈleʒər/', meaning: 'n. 休闲；空闲' },
  { word: 'liable', phonetic: '/ˈlaɪəbl/', meaning: 'adj. 有责任的；易于…的' },
  { word: 'liberal', phonetic: '/ˈlɪbərəl/', meaning: 'adj. 自由的；开明的' },
  { word: 'liberty', phonetic: '/ˈlɪbəti/', meaning: 'n. 自由' },
  { word: 'likewise', phonetic: '/ˈlaɪkwaɪz/', meaning: 'adv. 同样地' },
  { word: 'limitation', phonetic: '/ˌlɪmɪˈteɪʃn/', meaning: 'n. 限制；局限' },
  { word: 'link', phonetic: '/lɪŋk/', meaning: 'v./n. 连接；联系' },
  { word: 'literacy', phonetic: '/ˈlɪtərəsi/', meaning: 'n. 读写能力' },
  { word: 'locate', phonetic: '/ləʊˈkeɪt/', meaning: 'v. 定位；位于' },
  { word: 'logical', phonetic: '/ˈlɒdʒɪkl/', meaning: 'adj. 逻辑的；合理的' },
  { word: 'loose', phonetic: '/luːs/', meaning: 'adj. 松的；宽松的' },
  { word: 'luxury', phonetic: '/ˈlʌkʃəri/', meaning: 'n. 奢侈；奢华' },
  { word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: 'v. 维持；保养' },
  { word: 'majority', phonetic: '/məˈdʒɒrəti/', meaning: 'n. 多数；大多数' },
  { word: 'manage', phonetic: '/ˈmænɪdʒ/', meaning: 'v. 管理；设法' },
  { word: 'manner', phonetic: '/ˈmænər/', meaning: 'n. 方式；礼貌' },
  { word: 'manufacture', phonetic: '/ˌmænjuˈfæktʃər/', meaning: 'v./n. 制造；生产' },
  { word: 'margin', phonetic: '/ˈmɑːrdʒɪn/', meaning: 'n. 边缘；利润' },
  { word: 'mass', phonetic: '/mæs/', meaning: 'n. 质量；大量' },
  { word: 'mature', phonetic: '/məˈtʃʊər/', meaning: 'adj. 成熟的' },
  { word: 'maximum', phonetic: '/ˈmæksɪməm/', meaning: 'n./adj. 最大值(的)' },
  { word: 'measure', phonetic: '/ˈmeʒər/', meaning: 'v. 测量 n. 措施' },
  { word: 'mechanism', phonetic: '/ˈmekənɪzəm/', meaning: 'n. 机制；机构' },
  { word: 'medium', phonetic: '/ˈmiːdiəm/', meaning: 'n. 媒体；媒介' },
  { word: 'mental', phonetic: '/ˈmentl/', meaning: 'adj. 精神的；心理的' },
  { word: 'merchant', phonetic: '/ˈmɜːrtʃənt/', meaning: 'n. 商人' },
  { word: 'mercy', phonetic: '/ˈmɜːrsi/', meaning: 'n. 仁慈；怜悯' },
  { word: 'mere', phonetic: '/mɪər/', meaning: 'adj. 仅仅的；纯粹的' },
  { word: 'merit', phonetic: '/ˈmerɪt/', meaning: 'n. 优点；功绩' },
  { word: 'method', phonetic: '/ˈmeθəd/', meaning: 'n. 方法' },
  { word: 'mild', phonetic: '/maɪld/', meaning: 'adj. 温和的；轻微的' },
  { word: 'minimum', phonetic: '/ˈmɪnɪməm/', meaning: 'n./adj. 最小值(的)' },
  { word: 'ministry', phonetic: '/ˈmɪnɪstri/', meaning: 'n. 部门； ministry' },
  { word: 'minor', phonetic: '/ˈmaɪnər/', meaning: 'adj. 次要的；较小的' },
  { word: 'miracle', phonetic: '/ˈmɪrəkl/', meaning: 'n. 奇迹' },
  { word: 'miserable', phonetic: '/ˈmɪzərəbl/', meaning: 'adj. 悲惨的；痛苦的' },
  { word: 'mislead', phonetic: '/mɪsˈliːd/', meaning: 'v. 误导' },
  { word: 'mission', phonetic: '/ˈmɪʃn/', meaning: 'n. 使命；任务' },
  { word: 'moderate', phonetic: '/ˈmɒdərət/', meaning: 'adj. 适度的；温和的' },
  { word: 'modify', phonetic: '/ˈmɒdɪfaɪ/', meaning: 'v. 修改；调整' },
  { word: 'monitor', phonetic: '/ˈmɒnɪtər/', meaning: 'v. 监控 n. 显示器' },
  { word: 'moral', phonetic: '/ˈmɒrəl/', meaning: 'adj. 道德的 n. 寓意' },
  { word: 'motion', phonetic: '/ˈməʊʃn/', meaning: 'n. 运动；动议' },
  { word: 'motivate', phonetic: '/ˈməʊtɪveɪt/', meaning: 'v. 激励；激发' },
  { word: 'motive', phonetic: '/ˈməʊtɪv/', meaning: 'n. 动机；目的' },
  { word: 'multiple', phonetic: '/ˈmʌltɪpl/', meaning: 'adj. 多重的；多个的' },
  { word: 'mutual', phonetic: '/ˈmjuːtʃuəl/', meaning: 'adj. 相互的；共同的' },
  { word: 'narrow', phonetic: '/ˈnærəʊ/', meaning: 'adj. 狭窄的 v. 变窄' },
  { word: 'navigate', phonetic: '/ˈnævɪɡeɪt/', meaning: 'v. 导航；航行' },
  { word: 'negative', phonetic: '/ˈneɡətɪv/', meaning: 'adj. 消极的；否定的' },
  { word: 'neglect', phonetic: '/nɪˈɡlekt/', meaning: 'v./n. 忽视；疏忽' },
  { word: 'negotiate', phonetic: '/nɪˈɡəʊʃieɪt/', meaning: 'v. 谈判；协商' },
  { word: 'neutral', phonetic: '/ˈnjuːtrəl/', meaning: 'adj. 中立的' },
  { word: 'noble', phonetic: '/ˈnəʊbl/', meaning: 'adj. 高尚的；贵族的' },
  { word: 'normal', phonetic: '/ˈnɔːrml/', meaning: 'adj. 正常的' },
  { word: 'notion', phonetic: '/ˈnəʊʃn/', meaning: 'n. 概念；观念' },
  { word: 'nuclear', phonetic: '/ˈnjuːkliər/', meaning: 'adj. 核的；原子能的' },
  { word: 'numerous', phonetic: '/ˈnjuːmərəs/', meaning: 'adj. 许多的' },
  { word: 'nutrition', phonetic: '/njuːˈtrɪʃn/', meaning: 'n. 营养' },
  { word: 'objection', phonetic: '/əbˈdʒekʃn/', meaning: 'n. 反对；异议' },
  { word: 'objective', phonetic: '/əbˈdʒektɪv/', meaning: 'adj. 客观的 n. 目标' },
  { word: 'oblige', phonetic: '/əˈblaɪdʒ/', meaning: 'v. 迫使；帮忙' },
  { word: 'observe', phonetic: '/əbˈzɜːrv/', meaning: 'v. 观察；遵守' },
  { word: 'obtain', phonetic: '/əbˈteɪn/', meaning: 'v. 获得' },
  { word: 'obvious', phonetic: '/ˈɒbviəs/', meaning: 'adj. 明显的' },
  { word: 'occasion', phonetic: '/əˈkeɪʒn/', meaning: 'n. 场合；时机' },
  { word: 'occupy', phonetic: '/ˈɒkjupaɪ/', meaning: 'v. 占据；使忙碌' },
  { word: 'occur', phonetic: '/əˈkɜːr/', meaning: 'v. 发生；出现' },
  { word: 'offend', phonetic: '/əˈfend/', meaning: 'v. 冒犯；犯罪' },
  { word: 'official', phonetic: '/əˈfɪʃl/', meaning: 'adj. 官方的 n. 官员' },
  { word: 'operate', phonetic: '/ˈɒpəreɪt/', meaning: 'v. 操作；运营' },
  { word: 'opinion', phonetic: '/əˈpɪnjən/', meaning: 'n. 观点；看法' },
  { word: 'opponent', phonetic: '/əˈpəʊnənt/', meaning: 'n. 对手；反对者' },
  { word: 'opportunity', phonetic: '/ˌɒpərˈtjuːnəti/', meaning: 'n. 机会' },
  { word: 'oppose', phonetic: '/əˈpəʊz/', meaning: 'v. 反对；对抗' },
  { word: 'option', phonetic: '/ˈɒpʃn/', meaning: 'n. 选择；选项' },
  { word: 'oral', phonetic: '/ˈɔːrəl/', meaning: 'adj. 口头的' },
  { word: 'origin', phonetic: '/ˈɒrɪdʒɪn/', meaning: 'n. 起源；出身' },
  { word: 'original', phonetic: '/əˈrɪdʒɪnl/', meaning: 'adj. 原始的；独创的' },
  { word: 'outcome', phonetic: '/ˈaʊtkʌm/', meaning: 'n. 结果' },
  { word: 'outline', phonetic: '/ˈaʊtlaɪn/', meaning: 'n. 大纲 v. 概述' },
  { word: 'output', phonetic: '/ˈaʊtpʊt/', meaning: 'n. 产量；输出' },
  { word: 'overcome', phonetic: '/ˌəʊvərˈkʌm/', meaning: 'v. 克服' },
  { word: 'overlook', phonetic: '/ˌəʊvərˈlʊk/', meaning: 'v. 忽视；俯瞰' },
  { word: 'overwhelm', phonetic: '/ˌəʊvərˈwelm/', meaning: 'v. 压倒；淹没' },
  { word: 'owe', phonetic: '/əʊ/', meaning: 'v. 欠；归功于' },
  { word: 'pace', phonetic: '/peɪs/', meaning: 'n. 步伐；速度' },
  { word: 'parallel', phonetic: '/ˈpærəlel/', meaning: 'adj. 平行的 n. 平行线' },
  { word: 'participate', phonetic: '/pɑːrˈtɪsɪpeɪt/', meaning: 'v. 参与；参加' },
  { word: 'particular', phonetic: '/pərˈtɪkjələr/', meaning: 'adj. 特定的；挑剔的' },
  { word: 'passion', phonetic: '/ˈpæʃn/', meaning: 'n. 热情；激情' },
  { word: 'passive', phonetic: '/ˈpæsɪv/', meaning: 'adj. 被动的' },
  { word: 'patience', phonetic: '/ˈpeɪʃns/', meaning: 'n. 耐心' },
  { word: 'pattern', phonetic: '/ˈpætn/', meaning: 'n. 模式；图案' },
  { word: 'penalty', phonetic: '/ˈpenəlti/', meaning: 'n. 处罚；罚款' },
  { word: 'perceive', phonetic: '/pərˈsiːv/', meaning: 'v. 察觉；理解' },
  { word: 'percentage', phonetic: '/pərˈsentɪdʒ/', meaning: 'n. 百分比' },
  { word: 'perform', phonetic: '/pərˈfɔːrm/', meaning: 'v. 执行；表演' },
  { word: 'permanent', phonetic: '/ˈpɜːrmənənt/', meaning: 'adj. 永久的' },
  { word: 'permit', phonetic: '/pərˈmɪt/', meaning: 'v. 允许 n. 许可证' },
  { word: 'persist', phonetic: '/pərˈsɪst/', meaning: 'v. 坚持；持续' },
  { word: 'perspective', phonetic: '/pərˈspektɪv/', meaning: 'n. 角度；视角' },
  { word: 'persuade', phonetic: '/pərˈsweɪd/', meaning: 'v. 说服；劝服' },
  { word: 'phenomenon', phonetic: '/fɪˈnɒmɪnən/', meaning: 'n. 现象' },
  { word: 'philosophy', phonetic: '/fɪˈlɒsəfi/', meaning: 'n. 哲学' },
  { word: 'physical', phonetic: '/ˈfɪzɪkl/', meaning: 'adj. 身体的；物理的' },
  { word: 'pledge', phonetic: '/pledʒ/', meaning: 'n./v. 保证；誓言' },
  { word: 'plot', phonetic: '/plɒt/', meaning: 'n. 情节；阴谋 v. 绘制' },
  { word: 'poison', phonetic: '/ˈpɔɪzn/', meaning: 'n. 毒药 v. 毒害' },
  { word: 'policy', phonetic: '/ˈpɒləsi/', meaning: 'n. 政策；保险单' },
  { word: 'polish', phonetic: '/ˈpɒlɪʃ/', meaning: 'v. 擦亮；润色' },
  { word: 'possess', phonetic: '/pəˈzes/', meaning: 'v. 拥有；具有' },
  { word: 'postpone', phonetic: '/pəʊstˈpəʊn/', meaning: 'v. 推迟；延期' },
  { word: 'potential', phonetic: '/pəˈtenʃl/', meaning: 'adj. 潜在的 n. 潜力' },
  { word: 'poverty', phonetic: '/ˈpɒvəti/', meaning: 'n. 贫穷' },
  { word: 'practise', phonetic: '/ˈpræktɪs/', meaning: 'v. 练习；实践' },
  { word: 'praise', phonetic: '/preɪz/', meaning: 'v./n. 赞扬' },
  { word: 'precede', phonetic: '/prɪˈsiːd/', meaning: 'v. 在…之前；先于' },
  { word: 'precious', phonetic: '/ˈpreʃəs/', meaning: 'adj. 珍贵的' },
  { word: 'precise', phonetic: '/prɪˈsaɪs/', meaning: 'adj. 精确的' },
  { word: 'predict', phonetic: '/prɪˈdɪkt/', meaning: 'v. 预测' },
  { word: 'prejudice', phonetic: '/ˈpredʒʊdɪs/', meaning: 'n. 偏见' },
  { word: 'preparation', phonetic: '/ˌprepəˈreɪʃn/', meaning: 'n. 准备' },
  { word: 'preserve', phonetic: '/prɪˈzɜːrv/', meaning: 'v. 保存；保护' },
  { word: 'pretend', phonetic: '/prɪˈtend/', meaning: 'v. 假装' },
  { word: 'previous', phonetic: '/ˈpriːviəs/', meaning: 'adj. 先前的' },
  { word: 'primarily', phonetic: '/praɪˈmerəli/', meaning: 'adv. 主要地' },
  { word: 'primary', phonetic: '/ˈpraɪməri/', meaning: 'adj. 主要的；初级的' },
  { word: 'principle', phonetic: '/ˈprɪnsəpl/', meaning: 'n. 原则；原理' },
  { word: 'privilege', phonetic: '/ˈprɪvəlɪdʒ/', meaning: 'n. 特权' },
  { word: 'proceed', phonetic: '/prəˈsiːd/', meaning: 'v. 继续进行' },
  { word: 'process', phonetic: '/ˈprəʊses/', meaning: 'n. 过程 v. 处理' },
  { word: 'profession', phonetic: '/prəˈfeʃn/', meaning: 'n. 职业' },
  { word: 'profile', phonetic: '/ˈprəʊfaɪl/', meaning: 'n. 简介；侧面' },
  { word: 'prohibit', phonetic: '/prəˈhɪbɪt/', meaning: 'v. 禁止' },
  { word: 'project', phonetic: '/ˈprɒdʒekt/', meaning: 'n. 项目 v. 投射' },
  { word: 'promote', phonetic: '/prəˈməʊt/', meaning: 'v. 促进；晋升' },
  { word: 'prompt', phonetic: '/prɒmpt/', meaning: 'adj. 迅速的 v. 促使' },
  { word: 'proportion', phonetic: '/prəˈpɔːrʃn/', meaning: 'n. 比例；部分' },
  { word: 'propose', phonetic: '/prəˈpəʊz/', meaning: 'v. 提议；求婚' },
  { word: 'prospect', phonetic: '/ˈprɒspekt/', meaning: 'n. 前景；展望' },
  { word: 'prosperity', phonetic: '/prɒˈsperəti/', meaning: 'n. 繁荣' },
  { word: 'protest', phonetic: '/prəˈtest/', meaning: 'v./n. 抗议' },
  { word: 'prove', phonetic: '/pruːv/', meaning: 'v. 证明' },
  { word: 'provision', phonetic: '/prəˈvɪʒn/', meaning: 'n. 供应；规定' },
  { word: 'psychology', phonetic: '/saɪˈkɒlədʒi/', meaning: 'n. 心理学' },
  { word: 'publish', phonetic: '/ˈpʌblɪʃ/', meaning: 'v. 出版；发表' },
  { word: 'purchase', phonetic: '/ˈpɜːrtʃəs/', meaning: 'v./n. 购买' },
  { word: 'pursue', phonetic: '/pərˈsjuː/', meaning: 'v. 追求；追赶' },
  { word: 'qualify', phonetic: '/ˈkwɒlɪfaɪ/', meaning: 'v. 使合格；有资格' },
  { word: 'quantity', phonetic: '/ˈkwɒntəti/', meaning: 'n. 数量' },
  { word: 'quit', phonetic: '/kwɪt/', meaning: 'v. 放弃；退出' },
  { word: 'quote', phonetic: '/kwəʊt/', meaning: 'v. 引用 n. 引言' },
  { word: 'random', phonetic: '/ˈrændəm/', meaning: 'adj. 随机的' },
  { word: 'range', phonetic: '/reɪndʒ/', meaning: 'n. 范围 v. 变动' },
  { word: 'rank', phonetic: '/ræŋk/', meaning: 'n. 等级 v. 排列' },
  { word: 'rapid', phonetic: '/ˈræpɪd/', meaning: 'adj. 快速的' },
  { word: 'ratio', phonetic: '/ˈreɪʃiəʊ/', meaning: 'n. 比率' },
  { word: 'react', phonetic: '/riˈækt/', meaning: 'v. 反应' },
  { word: 'realistic', phonetic: '/ˌriːəˈlɪstɪk/', meaning: 'adj. 现实的' },
  { word: 'recession', phonetic: '/rɪˈseʃn/', meaning: 'n. 衰退' },
  { word: 'recognize', phonetic: '/ˈrekəɡnaɪz/', meaning: 'v. 认出；承认' },
  { word: 'recommend', phonetic: '/ˌrekəˈmend/', meaning: 'v. 推荐；建议' },
  { word: 'recover', phonetic: '/rɪˈkʌvər/', meaning: 'v. 恢复' },
  { word: 'reduction', phonetic: '/rɪˈdʌkʃn/', meaning: 'n. 减少' },
  { word: 'refer', phonetic: '/rɪˈfɜːr/', meaning: 'v. 提到；参考' },
  { word: 'reflect', phonetic: '/rɪˈflekt/', meaning: 'v. 反映；反射' },
  { word: 'reform', phonetic: '/rɪˈfɔːrm/', meaning: 'v./n. 改革' },
  { word: 'refresh', phonetic: '/rɪˈfreʃ/', meaning: 'v. 使恢复；刷新' },
  { word: 'refuse', phonetic: '/rɪˈfjuːz/', meaning: 'v. 拒绝' },
  { word: 'regard', phonetic: '/rɪˈɡɑːrd/', meaning: 'v. 看待 n. 尊重' },
  { word: 'register', phonetic: '/ˈredʒɪstər/', meaning: 'v. 注册 n. 登记簿' },
  { word: 'regulate', phonetic: '/ˈreɡjuleɪt/', meaning: 'v. 管理；调节' },
  { word: 'reinforce', phonetic: '/ˌriːɪnˈfɔːrs/', meaning: 'v. 加强；增援' },
  { word: 'reject', phonetic: '/rɪˈdʒekt/', meaning: 'v. 拒绝；排斥' },
  { word: 'relate', phonetic: '/rɪˈleɪt/', meaning: 'v. 联系；叙述' },
  { word: 'relative', phonetic: '/ˈrelətɪv/', meaning: 'n. 亲属 adj. 相对的' },
  { word: 'release', phonetic: '/rɪˈliːs/', meaning: 'v./n. 释放；发布' },
  { word: 'relevant', phonetic: '/ˈreləvənt/', meaning: 'adj. 相关的' },
  { word: 'reliable', phonetic: '/rɪˈlaɪəbl/', meaning: 'adj. 可靠的' },
  { word: 'relief', phonetic: '/rɪˈliːf/', meaning: 'n. 减轻；救济' },
  { word: 'reluctant', phonetic: '/rɪˈlʌktənt/', meaning: 'adj. 不情愿的' },
  { word: 'rely', phonetic: '/rɪˈlaɪ/', meaning: 'v. 依赖；依靠' },
  { word: 'remain', phonetic: '/rɪˈmeɪn/', meaning: 'v. 保持；剩余' },
  { word: 'remark', phonetic: '/rɪˈmɑːrk/', meaning: 'v./n. 评论；言辞' },
  { word: 'remedy', phonetic: '/ˈremədi/', meaning: 'n. 补救办法 v. 纠正' },
  { word: 'remote', phonetic: '/rɪˈməʊt/', meaning: 'adj. 偏远的；遥远的' },
  { word: 'render', phonetic: '/ˈrendər/', meaning: 'v. 使成为；给予' },
  { word: 'renew', phonetic: '/rɪˈnjuː/', meaning: 'v. 更新；续期' },
  { word: 'represent', phonetic: '/ˌreprɪˈzent/', meaning: 'v. 代表；表示' },
  { word: 'reproduce', phonetic: '/ˌriːprəˈdjuːs/', meaning: 'v. 复制；繁殖' },
  { word: 'reputation', phonetic: '/ˌrepjuˈteɪʃn/', meaning: 'n. 名声；声誉' },
  { word: 'require', phonetic: '/rɪˈkwaɪər/', meaning: 'v. 要求；需要' },
  { word: 'resemble', phonetic: '/rɪˈzembl/', meaning: 'v. 类似；像' },
  { word: 'reserve', phonetic: '/rɪˈzɜːrv/', meaning: 'v. 预订 n. 储备' },
  { word: 'resident', phonetic: '/ˈrezɪdənt/', meaning: 'n. 居民' },
  { word: 'resign', phonetic: '/rɪˈzaɪn/', meaning: 'v. 辞职' },
  { word: 'resist', phonetic: '/rɪˈzɪst/', meaning: 'v. 抵抗；抵制' },
  { word: 'resolve', phonetic: '/rɪˈzɒlv/', meaning: 'v. 解决；决心' },
  { word: 'resource', phonetic: '/rɪˈzɔːrs/', meaning: 'n. 资源' },
  { word: 'respond', phonetic: '/rɪˈspɒnd/', meaning: 'v. 回应；反应' },
  { word: 'restore', phonetic: '/rɪˈstɔːr/', meaning: 'v. 恢复；修复' },
  { word: 'restrict', phonetic: '/rɪˈstrɪkt/', meaning: 'v. 限制' },
  { word: 'retain', phonetic: '/rɪˈteɪn/', meaning: 'v. 保留；保持' },
  { word: 'retire', phonetic: '/rɪˈtaɪər/', meaning: 'v. 退休' },
  { word: 'reveal', phonetic: '/rɪˈviːl/', meaning: 'v. 揭露；显示' },
  { word: 'revenue', phonetic: '/ˈrevənjuː/', meaning: 'n. 收入；税收' },
  { word: 'reverse', phonetic: '/rɪˈvɜːrs/', meaning: 'v. 颠倒 adj. 相反的' },
  { word: 'revise', phonetic: '/rɪˈvaɪz/', meaning: 'v. 修改；复习' },
  { word: 'revolution', phonetic: '/ˌrevəˈluːʃn/', meaning: 'n. 革命' },
  { word: 'reward', phonetic: '/rɪˈwɔːrd/', meaning: 'n. 报酬 v. 奖赏' },
  { word: 'risk', phonetic: '/rɪsk/', meaning: 'n. 风险 v. 冒险' },
  { word: 'routine', phonetic: '/ruːˈtiːn/', meaning: 'n. 常规 adj. 日常的' },
  { word: 'sacrifice', phonetic: '/ˈsækrɪfaɪs/', meaning: 'v./n. 牺牲' },
  { word: 'salary', phonetic: '/ˈsæləri/', meaning: 'n. 薪水' },
  { word: 'sample', phonetic: '/ˈsɑːrmpl/', meaning: 'n. 样品 v. 采样' },
  { word: 'satisfy', phonetic: '/ˈsætɪsfaɪ/', meaning: 'v. 满足；使满意' },
  { word: 'scale', phonetic: '/skeɪl/', meaning: 'n. 规模；刻度' },
  { word: 'scandal', phonetic: '/ˈskændl/', meaning: 'n. 丑闻' },
  { word: 'scatter', phonetic: '/ˈskætər/', meaning: 'v. 散开；撒播' },
  { word: 'schedule', phonetic: '/ˈʃedjuːl/', meaning: 'n. 时间表 v. 安排' },
  { word: 'scheme', phonetic: '/skiːm/', meaning: 'n. 计划；方案' },
  { word: 'scholarship', phonetic: '/ˈskɒləʃɪp/', meaning: 'n. 奖学金' },
  { word: 'scope', phonetic: '/skəʊp/', meaning: 'n. 范围；机会' },
  { word: 'secure', phonetic: '/sɪˈkjʊər/', meaning: 'adj. 安全的 v. 获得' },
  { word: 'separate', phonetic: '/ˈsepəreɪt/', meaning: 'v. 分离 adj. 单独的' },
  { word: 'sequence', phonetic: '/ˈsiːkwəns/', meaning: 'n. 顺序；序列' },
  { word: 'session', phonetic: '/ˈseʃn/', meaning: 'n. 会议；一段时间' },
  { word: 'settle', phonetic: '/ˈsetl/', meaning: 'v. 解决；定居' },
  { word: 'severe', phonetic: '/sɪˈvɪər/', meaning: 'adj. 严重的；严厉的' },
  { word: 'shelter', phonetic: '/ˈʃeltər/', meaning: 'n. 避难所 v. 庇护' },
  { word: 'shift', phonetic: '/ʃɪft/', meaning: 'v. 转移 n. 轮班' },
  { word: 'shortage', phonetic: '/ˈʃɔːrtɪdʒ/', meaning: 'n. 短缺' },
  { word: 'signal', phonetic: '/ˈsɪɡnl/', meaning: 'n. 信号 v. 发信号' },
  { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: 'adj. 重要的；显著的' },
  { word: 'simplify', phonetic: '/ˈsɪmplɪfaɪ/', meaning: 'v. 简化' },
  { word: 'simulate', phonetic: '/ˈsɪmjuleɪt/', meaning: 'v. 模拟' },
  { word: 'situation', phonetic: '/ˌsɪtʃuˈeɪʃn/', meaning: 'n. 情况；处境' },
  { word: 'slight', phonetic: '/slaɪt/', meaning: 'adj. 轻微的' },
  { word: 'slim', phonetic: '/slɪm/', meaning: 'adj. 苗条的；微小的' },
  { word: 'solution', phonetic: '/səˈluːʃn/', meaning: 'n. 解决方案；溶液' },
  { word: 'sophisticated', phonetic: '/səˈfɪstɪkeɪtɪd/', meaning: 'adj. 复杂的；精密的' },
  { word: 'source', phonetic: '/sɔːrs/', meaning: 'n. 来源' },
  { word: 'specific', phonetic: '/spəˈsɪfɪk/', meaning: 'adj. 具体的；特定的' },
  { word: 'sponsor', phonetic: '/ˈspɒnsər/', meaning: 'n. 赞助者 v. 赞助' },
  { word: 'stable', phonetic: '/ˈsteɪbl/', meaning: 'adj. 稳定的' },
  { word: 'standard', phonetic: '/ˈstændərd/', meaning: 'n. 标准 adj. 标准的' },
  { word: 'statement', phonetic: '/ˈsteɪtmənt/', meaning: 'n. 声明；陈述' },
  { word: 'status', phonetic: '/ˈsteɪtəs/', meaning: 'n. 地位；状态' },
  { word: 'steady', phonetic: '/ˈstedi/', meaning: 'adj. 稳定的；平稳的' },
  { word: 'stimulate', phonetic: '/ˈstɪmjuleɪt/', meaning: 'v. 刺激；激励' },
  { word: 'strategy', phonetic: '/ˈstrætədʒi/', meaning: 'n. 策略；战略' },
  { word: 'strength', phonetic: '/streŋθ/', meaning: 'n. 力量；优势' },
  { word: 'stress', phonetic: '/stres/', meaning: 'n. 压力；强调' },
  { word: 'stretch', phonetic: '/stretʃ/', meaning: 'v. 延伸；伸展' },
  { word: 'structure', phonetic: '/ˈstrʌktʃər/', meaning: 'n. 结构 v. 组织' },
  { word: 'submit', phonetic: '/səbˈmɪt/', meaning: 'v. 提交；服从' },
  { word: 'substance', phonetic: '/ˈsʌbstəns/', meaning: 'n. 物质；实质' },
  { word: 'substitute', phonetic: '/ˈsʌbstɪtjuːt/', meaning: 'n. 替代品 v. 替代' },
  { word: 'succeed', phonetic: '/səkˈsiːd/', meaning: 'v. 成功；继承' },
  { word: 'sufficient', phonetic: '/səˈfɪʃnt/', meaning: 'adj. 足够的' },
  { word: 'suggest', phonetic: '/səˈdʒest/', meaning: 'v. 建议；暗示' },
  { word: 'superior', phonetic: '/suːˈpɪəriər/', meaning: 'adj. 优越的 n. 上司' },
  { word: 'supplement', phonetic: '/ˈsʌplɪmənt/', meaning: 'n. 补充 v. 增补' },
  { word: 'supply', phonetic: '/səˈplaɪ/', meaning: 'v./n. 供应' },
  { word: 'suppose', phonetic: '/səˈpəʊz/', meaning: 'v. 假设；认为' },
  { word: 'surface', phonetic: '/ˈsɜːrfɪs/', meaning: 'n. 表面 v. 浮出' },
  { word: 'surplus', phonetic: '/ˈsɜːrpləs/', meaning: 'n. 剩余 adj. 过剩的' },
  { word: 'survive', phonetic: '/sərˈvaɪv/', meaning: 'v. 幸存；存活' },
  { word: 'suspect', phonetic: '/səˈspekt/', meaning: 'v. 怀疑 n. 嫌疑人' },
  { word: 'suspend', phonetic: '/səˈspend/', meaning: 'v. 暂停；悬挂' },
  { word: 'sustain', phonetic: '/səˈsteɪn/', meaning: 'v. 维持；支撑' },
  { word: 'symbol', phonetic: '/ˈsɪmbl/', meaning: 'n. 象征；符号' },
  { word: 'sympathy', phonetic: '/ˈsɪmpəθi/', meaning: 'n. 同情' },
  { word: 'symptom', phonetic: '/ˈsɪmptəm/', meaning: 'n. 症状' },
  { word: 'technique', phonetic: '/tekˈniːk/', meaning: 'n. 技术；技巧' },
  { word: 'temporary', phonetic: '/ˈtempərəri/', meaning: 'adj. 暂时的' },
  { word: 'tend', phonetic: '/tend/', meaning: 'v. 倾向于；照管' },
  { word: 'tendency', phonetic: '/ˈtendənsi/', meaning: 'n. 趋势；倾向' },
  { word: 'terminal', phonetic: '/ˈtɜːrmɪnl/', meaning: 'n. 航站楼 adj. 末期的' },
  { word: 'territory', phonetic: '/ˈterɪtəri/', meaning: 'n. 领土；领域' },
  { word: 'threat', phonetic: '/θret/', meaning: 'n. 威胁' },
  { word: 'threshold', phonetic: '/ˈθreʃhəʊld/', meaning: 'n. 门槛；临界点' },
  { word: 'tolerate', phonetic: '/ˈtɒləreɪt/', meaning: 'v. 容忍；忍受' },
  { word: 'transfer', phonetic: '/trænsˈfɜːr/', meaning: 'v. 转移；转让' },
  { word: 'transform', phonetic: '/trænsˈfɔːrm/', meaning: 'v. 转变；改造' },
  { word: 'transition', phonetic: '/trænˈzɪʃn/', meaning: 'n. 过渡；转变' },
  { word: 'transmit', phonetic: '/trænzˈmɪt/', meaning: 'v. 传输；传播' },
  { word: 'transparent', phonetic: '/trænsˈpærənt/', meaning: 'adj. 透明的；坦率的' },
  { word: 'trend', phonetic: '/trend/', meaning: 'n. 趋势' },
  { word: 'trial', phonetic: '/ˈtraɪəl/', meaning: 'n. 审判；试验' },
  { word: 'trigger', phonetic: '/ˈtrɪɡər/', meaning: 'v. 触发 n. 扳机' },
  { word: 'typical', phonetic: '/ˈtɪpɪkl/', meaning: 'adj. 典型的' },
  { word: 'ultimate', phonetic: '/ˈʌltɪmət/', meaning: 'adj. 最终的；根本的' },
  { word: 'undergo', phonetic: '/ˌʌndərˈɡəʊ/', meaning: 'v. 经历；承受' },
  { word: 'undertake', phonetic: '/ˌʌndərˈteɪk/', meaning: 'v. 承担；从事' },
  { word: 'uniform', phonetic: '/ˈjuːnɪfɔːrm/', meaning: 'n. 制服 adj. 统一的' },
  { word: 'unique', phonetic: '/juːˈniːk/', meaning: 'adj. 独特的' },
  { word: 'universal', phonetic: '/ˌjuːnɪˈvɜːrsl/', meaning: 'adj. 普遍的；全世界的' },
  { word: 'update', phonetic: '/ʌpˈdeɪt/', meaning: 'v./n. 更新' },
  { word: 'upgrade', phonetic: '/ʌpˈɡreɪd/', meaning: 'v./n. 升级' },
  { word: 'upright', phonetic: '/ˈʌpraɪt/', meaning: 'adj. 直立的；正直的' },
  { word: 'upset', phonetic: '/ʌpˈset/', meaning: 'adj. 心烦的 v. 打乱' },
  { word: 'urban', phonetic: '/ˈɜːrbən/', meaning: 'adj. 城市的' },
  { word: 'urge', phonetic: '/ɜːrdʒ/', meaning: 'v. 敦促 n. 冲动' },
  { word: 'urgent', phonetic: '/ˈɜːrdʒənt/', meaning: 'adj. 紧急的' },
  { word: 'utilize', phonetic: '/ˈjuːtɪlaɪz/', meaning: 'v. 利用' },
  { word: 'vacant', phonetic: '/ˈveɪkənt/', meaning: 'adj. 空的；空缺的' },
  { word: 'valid', phonetic: '/ˈvælɪd/', meaning: 'adj. 有效的；合理的' },
  { word: 'value', phonetic: '/ˈvæljuː/', meaning: 'n. 价值 v. 重视' },
  { word: 'vanish', phonetic: '/ˈvænɪʃ/', meaning: 'v. 消失' },
  { word: 'variety', phonetic: '/vəˈraɪəti/', meaning: 'n. 多样性；种类' },
  { word: 'vast', phonetic: '/vɑːst/', meaning: 'adj. 广阔的；巨大的' },
  { word: 'venture', phonetic: '/ˈventʃər/', meaning: 'n. 冒险 v. 敢于' },
  { word: 'verify', phonetic: '/ˈverɪfaɪ/', meaning: 'v. 核实；证实' },
  { word: 'version', phonetic: '/ˈvɜːrʃn/', meaning: 'n. 版本' },
  { word: 'vertical', phonetic: '/ˈvɜːrtɪkl/', meaning: 'adj. 垂直的' },
  { word: 'victim', phonetic: '/ˈvɪktɪm/', meaning: 'n. 受害者' },
  { word: 'violence', phonetic: '/ˈvaɪələns/', meaning: 'n. 暴力' },
  { word: 'virtue', phonetic: '/ˈvɜːrtʃuː/', meaning: 'n. 美德；优点' },
  { word: 'visible', phonetic: '/ˈvɪzəbl/', meaning: 'adj. 可见的' },
  { word: 'vision', phonetic: '/ˈvɪʒn/', meaning: 'n. 视力；远见' },
  { word: 'vital', phonetic: '/ˈvaɪtl/', meaning: 'adj. 至关重要的' },
  { word: 'vivid', phonetic: '/ˈvɪvɪd/', meaning: 'adj. 生动的' },
  { word: 'vocabulary', phonetic: '/vəˈkæbjələri/', meaning: 'n. 词汇' },
  { word: 'voluntary', phonetic: '/ˈvɒləntri/', meaning: 'adj. 自愿的' },
  { word: 'welfare', phonetic: '/ˈwelfeər/', meaning: 'n. 福利' },
  { word: 'withdraw', phonetic: '/wɪðˈdrɔː/', meaning: 'v. 撤回；提取' },
  { word: 'witness', phonetic: '/ˈwɪtnəs/', meaning: 'n. 目击者 v. 见证' },
  { word: 'worship', phonetic: '/ˈwɜːrʃɪp/', meaning: 'v./n. 崇拜' },
  { word: 'yield', phonetic: '/jiːld/', meaning: 'v. 产出；屈服 n. 产量' },
  { word: 'zone', phonetic: '/zəʊn/', meaning: 'n. 区域；地带' },
]

async function main() {
  let success = 0
  let fail = 0
  for (const w of words) {
    try {
      const res = await fetch(`${API_BASE}/words`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(w),
      })
      if (res.ok) success++
      else fail++
    } catch {
      fail++
    }
  }
  console.log(`Done: ${success} success, ${fail} fail, ${words.length} total`)
}

main()
